import assert from 'node:assert/strict';
import fs from 'node:fs';

const background = fs.readFileSync(new URL('../src/background.js', import.meta.url), 'utf8');
const messages = fs.readFileSync(new URL('../src/shared/messages.js', import.meta.url), 'utf8');
const manifest = JSON.parse(fs.readFileSync(new URL('../manifest.json', import.meta.url), 'utf8'));
const ui = fs.readFileSync(new URL('../src/ui/operator-companion.js', import.meta.url), 'utf8');

assert.match(messages, /AI_CHAT_REQUEST/);
assert.match(messages, /AI_CHAT_STATE_GET/);
assert.match(messages, /AI_CHAT_RESET/);
assert.match(background, /handleAiChatRequest/);
assert.match(background, /handleAiChatStateGet/);
assert.match(background, /handleAiChatReset/);
assert.match(background, /buildAiContext/);
assert.match(background, /COMPACT CASE SNAPSHOT/);
assert.match(background, /SELECTED PLAYBOOK CARDS/);
assert.match(background, /actualPromptTokens/);
assert.match(background, /AI_SYSTEM_PROMPT/);
assert.match(background, /fetch\(`\$\{AI_CONFIG\.baseUrl\}\/chat\/completions`/);
assert.match(background, /Твой собеседник — ОПЕРАТОР|Отвечай только на сообщение оператора/i);
assert.match(background, /главный разделитель|2–4 КОРОТКИХ связанных/i, 'agent must use high-information discriminators without becoming a one-question wizard');
assert.match(background, /Не жди, пока оператор каждый раз спросит «а ещё\?»/i, 'agent must proactively continue an open diagnostic branch');
assert.match(background, /aiCompletionBudgetFor/, 'open diagnostic requests must get a larger completion budget');
assert.match(background, /deriveOperatorDialogMemory/, 'operator facts must be captured before the next model call');
assert.match(background, /reasoning_format:\s*'hidden'/, 'reasoning must never be returned to operator UI');
assert.match(background, /reasoning_effort: options\.reasoningEffort === 'default' \? 'default' : 'none'/, 'routine operator chat should not burn reasoning tokens by default');
assert.match(background, /aiReasoningEffortFor/, 'explicit deep-analysis requests may enable reasoning');
assert.doesNotMatch(background, /response_format:\s*\{\s*type:\s*'json_object'/, 'routine chat must not fail solely because JSON Object Mode failed');
assert.match(background, /<wb_memory>/, 'dialog memory must travel in a non-fatal hidden tail of the same completion');
assert.match(background, /aiParseAssistantContent/, 'plain-text operator answer must survive malformed memory metadata');
assert.match(background, /ПРЯМЫЕ ВОПРОСЫ|спрашивает «сколько норма/, 'direct operator questions must be answered directly');
assert.match(background, /Тариф называй только из snapshot\.tariff\.speedMbps/, 'tariff must not be inferred or hallucinated from measurements');
assert.match(background, /TARIFF FACT LOCK/, 'explicit tariff speed must be locked from snapshot for every request');
assert.match(background, /DIALOG MEMORY/);
assert.match(background, /Context Builder|buildAiContext|compact snapshot/i);
assert.match(background, /aiRecentHistory\(session, 6\)/, 'literal chat history must be bounded');
assert.match(background, /chrome\.storage\?\.session|storage\?\.session/, 'AI session must survive content-script/page reloads in background session storage');
assert.match(background, /prompt_tokens/);
assert.match(background, /completion_tokens/);
assert.match(background, /total_tokens/);
assert.doesNotMatch(ui, /AI_CONFIG|Authorization|Bearer|gsk_/);
assert.ok(manifest.host_permissions.includes('https://api.groq.com/*'));
assert.doesNotMatch(JSON.stringify(manifest), /gsk_[A-Za-z0-9_-]+/);
console.log('ai_background_contract_test: PASS');
