import assert from 'node:assert/strict';
import { createRefreshGate } from '../src/features/call/background/refresh-gate.js';
let time = 1000;
let count = 0;
const gate = createRefreshGate(() => time);
const fetch = async () => ({ refreshed: true, sequence: ++count });
const first = gate('idle', fetch);
assert.equal(gate('idle', fetch), first, 'simultaneous refreshes share one operation');
await first;
assert.equal((await gate('idle', fetch, true)).sequence, 1);
assert.equal((await gate('idle', fetch)).sequence, 2, 'independent click is fresh');
await gate('active', fetch, true);
assert.equal(count, 3, 'activity transition invalidates reuse');
time += 16000;
await gate('active', fetch, true);
assert.equal(count, 4, 'expired result is not reused');
await assert.rejects(gate('failure', async () => { throw new Error('offline'); }));
await gate('failure', fetch, true);
assert.equal(count, 5, 'failed operation releases gate');
console.log('refresh gate: PASS');
