import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=rel=>fs.readFileSync(path.join(ROOT,rel),'utf8');
const walk=dir=>fs.readdirSync(path.join(ROOT,dir),{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]).filter(f=>/\.js$/.test(f));
const source=walk('src').map(read).join('\n');
assert.doesNotMatch(source,/\bsetInterval\s*\(/);
assert.doesNotMatch(source,/observability|field.?log|operator.?trace|performance.?monitor|action.?session|guide-loader|WB\.guide/i);
for(const removed of ['src/browser/actions/fill-billing-technical.js','src/browser/actions/show-save-hint.js','src/ui/guide.js','src/ui/guide-loader.js','src/core/action-lifecycle.js']) assert.equal(fs.existsSync(path.join(ROOT,removed)),false,`${removed} removed`);
const manifest=JSON.parse(read('manifest.json')); const scripts=manifest.content_scripts?.[0]?.js||[];
assert.ok(scripts.includes('src/core/juniper-prefetch.js'));
assert.ok(scripts.includes('src/browser/actions/focus-userside-tmc.js'));
assert.equal(scripts.some(x=>/fill-billing-technical|show-save-hint|guide/.test(x)),false);
assert.doesNotMatch(read('src/content/bootstrap.js'),/new\s+MutationObserver|addEventListener\(['"]change/);
assert.match(read('src/core/interaction-guards.js'),/new\s+MutationObserver/);
assert.match(read('src/core/interaction-guards.js'),/pollResponseObserver\?\.disconnect/);
assert.match(read('src/core/interaction-guards.js'),/poll-response-timeout/);
assert.match(read('src/browser/actions/focus-userside-tmc.js'),/new\s+MutationObserver/);
console.log('hard_direct_runtime_contract_test: PASS');
