import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const runtime = fs.readFileSync(new URL('../src/ui/operator-companion.js', import.meta.url), 'utf8');
const contentSource = fs.readFileSync(new URL('../src/ui/operator-companion-content.js', import.meta.url), 'utf8');
const loader = fs.readFileSync(new URL('../src/ui/operator-companion-loader.js', import.meta.url), 'utf8');
const rail = fs.readFileSync(new URL('../src/ui/rail.js', import.meta.url), 'utf8');
const bootstrap = fs.readFileSync(new URL('../src/content/bootstrap.js', import.meta.url), 'utf8');
const featureLoader = fs.readFileSync(new URL('../src/infrastructure/feature-loader.js', import.meta.url), 'utf8');

assert.match(runtime, /WB\.store\?\.activeCase/, 'AI Companion must consume the already-built Workbench case context');
assert.match(runtime, /episodeId/, 'AI session identity must include episodeId');
assert.match(runtime, /AI_CHAT_REQUEST/, 'AI Companion must call the background AI request message');
assert.match(runtime, /AI_CHAT_STATE_GET/, 'AI Companion must restore chat after navigation/reload');
assert.match(runtime, /AI_CHAT_RESET/, 'new dialog must clear only the current AI session');
assert.match(runtime, /operatorCompanionContent\?\.forAgent/, 'old Graph content must be consumed as the AI playbook');
assert.match(runtime, /AI напарник/);
assert.match(runtime, /Новый диалог/);
assert.match(runtime, /Диалог привязан к текущему обращению/);
assert.match(runtime, /promptTokens/);
assert.match(runtime, /completionTokens/);
assert.match(runtime, /totalTokens/);
assert.match(runtime, /Фактический usage этого запроса/);
assert.match(runtime, /<strong>/, 'assistant must support safe emphasis for key facts/actions');
assert.match(runtime, /height:min\(420px/, 'chat must remain a compact helper panel');
assert.match(runtime, /aria-modal=\"false\"/, 'chat must not block the CRM while operator performs checks');
assert.doesNotMatch(runtime, /gsk_[A-Za-z0-9_-]+/, 'API key must never be present in Companion UI code');
assert.doesNotMatch(runtime, /\bfetch\s*\(/, 'Companion UI must not call Groq directly');
assert.doesNotMatch(runtime, /Диагностический Graph|Что спросить|Что это может значить|Что предложить сделать/, 'old visual Graph UI must be gone');
assert.match(rail, /view-companion/);
assert.match(rail, /AI помощник/);
assert.match(rail, /AI_CHAT_STATE_GET/, 'case export must enrich export with the current AI dialog');
assert.doesNotMatch(rail, /Диагностический Graph|view-graph|operatorGraph|appealView|Навигатор обращения/i);
assert.match(featureLoader, /companion: Object\.freeze\(\[\s*'src\/ui\/operator-companion-content\.js',\s*'src\/ui\/operator-companion\.js'\s*\]\)/);
assert.match(loader, /feature: 'companion'/);
assert.match(bootstrap, /WB\.operatorCompanion\?\.destroy\?\.\(\)/, 'runtime destroy must tear down a loaded Companion');

const sandbox = { SIMNET_WB: {} };
sandbox.globalThis = sandbox;
vm.createContext(sandbox);
vm.runInContext(contentSource, sandbox);
const catalog = sandbox.SIMNET_WB.operatorCompanionContent;
assert.equal(catalog.types.length, 6);
const phraseCount = catalog.types.reduce((sum, topic) => sum + topic.phrases.length, 0);
assert.equal(phraseCount, 48, 'diagnostic knowledge from the old Graph must be retained');
assert.ok(catalog.search('вылогинивает').some(row => row.typeId === 'apps_slow'));
const playbook = catalog.forAgent('низкая скорость по wifi 300 на всех устройствах');
assert.equal(playbook.mode, 'focused');
assert.ok(playbook.topicIds.includes('low_speed'));
assert.ok(playbook.cards.some(item => item.id === 'wifi_band'));
assert.ok(playbook.cards.some(item => item.id === 'wifi_distance'));
assert.ok(playbook.cards.some(item => item.id === 'multiple_macs'), 'master playbook cards stay local even when not selected for prompt');
assert.match(runtime, /renderContextInspector/, 'operator must be able to inspect actual AI context');
assert.match(runtime, />Контекст</, 'each answer must expose a compact context inspector');
console.log('operator_companion_contract_test: PASS', { topics: catalog.types.length, phraseCount, suggested: playbook.suggestedCardIds });
