import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const runtime = fs.readFileSync(new URL('../src/ui/operator-companion-conversation.js', import.meta.url), 'utf8');
const backend = fs.readFileSync(new URL('../src/features/operator-companion/background.js', import.meta.url), 'utf8');
const contentSource = fs.readFileSync(new URL('../src/ui/operator-companion-content.js', import.meta.url), 'utf8');
const loader = fs.readFileSync(new URL('../src/ui/operator-companion-loader.js', import.meta.url), 'utf8');
const rail = fs.readFileSync(new URL('../src/ui/rail.js', import.meta.url), 'utf8');
const bootstrap = fs.readFileSync(new URL('../src/content/bootstrap.js', import.meta.url), 'utf8');
const featureLoader = fs.readFileSync(new URL('../src/infrastructure/feature-loader.js', import.meta.url), 'utf8');
const legacyControlsGate = fs.readFileSync(new URL('../src/ui/operator-companion-session-controls-disable.js', import.meta.url), 'utf8');
const backgroundEntry = fs.readFileSync(new URL('../src/background-entry.js', import.meta.url), 'utf8');

assert.doesNotMatch(runtime, /WB\.store\?\.activeCase|currentIdentity\(|caseId::|episodeId/, 'Companion conversation must not be owned by the active CRM Case');
assert.match(runtime, /companion:operator/, 'Companion must use one continuous operator conversation');
assert.match(runtime, /COMPANION_CHAT_REQUEST/, 'Companion must use its dedicated background request');
assert.match(runtime, /COMPANION_CHAT_STATE_GET/, 'Companion must restore its persistent conversation');
assert.match(runtime, /COMPANION_CHAT_RESET/, 'new dialog must reset Companion conversation/work episodes');
assert.doesNotMatch(runtime, /AI_CHAT_REQUEST|AI_CHAT_STATE_GET|AI_CHAT_RESET/, 'legacy case-bound AI_CHAT channel must not own the new Companion UI');
assert.match(runtime, /operatorCompanionContent\?\.forAgent/, 'diagnostic playbook remains available as local guidance');
assert.match(runtime, /AI напарник/);
assert.match(runtime, /Свободный диалог/);
assert.match(runtime, /CRM-кейс не требуется/);
assert.match(runtime, /READ-проверки/, 'operator can inspect which read-only tools were used');
assert.match(runtime, /promptTokens/);
assert.match(runtime, /completionTokens/);
assert.match(runtime, /totalTokens/);
assert.match(runtime, /<strong>/, 'assistant supports safe emphasis');
assert.match(runtime, /height:min\(470px/, 'chat remains a compact helper panel');
assert.match(runtime, /aria-modal=\"false\"/, 'chat must not block CRM while operator performs checks');
assert.doesNotMatch(runtime, /gsk_[A-Za-z0-9_-]+/, 'API key must never be present in Companion UI code');
assert.doesNotMatch(runtime, /\bfetch\s*\(/, 'Companion UI must not call Groq or CRM directly');
assert.doesNotMatch(runtime, /Диалог привязан к текущему обращению|Кейс не определён/, 'case-bound copy must be gone');

assert.match(backend, /live-tool-runtime\.js/, 'Companion backend must reuse the shared live READ tool runtime');
assert.match(backend, /MAX_TOOL_CALLS\s*=\s*4/, 'tool chaining must stay bounded');
assert.match(backend, /COMPANION_CHAT_REQUEST/);
assert.match(backend, /COMPANION_CHAT_STATE_GET/);
assert.match(backend, /COMPANION_CHAT_RESET/);
assert.match(backend, /<wb_tool_request>/, 'model has an explicit bounded tool request protocol');
assert.match(backend, /READ-инструменты|READ-инструмент|READ-only/i, 'Companion prompt must keep tools read-only');
assert.match(backend, /Никогда не смешивай факты разных абонентов/, 'target isolation must be part of the model contract');
assert.match(backend, /Обычная беседа|обычный разговор|обычной беседы/i, 'general conversation must remain valid without creating a case');
assert.doesNotMatch(backend, /ведёшь обычный живой чат с абонентом/i, 'subscriber-facing Autonomous Operator persona must not leak into Companion');

assert.match(featureLoader, /operator-companion-content\.js/);
assert.match(featureLoader, /operator-companion-conversation\.js/);
assert.match(featureLoader, /operator-companion-session-controls-disable\.js/);
assert.match(featureLoader, /operator-companion-session-controls\.js/, 'legacy session-controls file remains loadable for compatibility');
assert.match(legacyControlsGate, /__operatorCompanionConversationLoaded/);
assert.match(legacyControlsGate, /__operatorCompanionSessionControlsLoaded\s*=\s*true/, 'persistent Companion must suppress legacy Start/End controls before they mount');
assert.match(backgroundEntry, /features\/operator-companion\/background\.js/, 'service worker entry must register Companion backend');
assert.match(loader, /feature: 'companion'/);
assert.match(bootstrap, /WB\.operatorCompanion\?\.destroy\?\.\(\)/, 'runtime destroy must tear down a loaded Companion');
assert.match(rail, /view-companion/);
assert.match(rail, /AI помощник/);
assert.doesNotMatch(rail, /Диагностический Graph|view-graph|operatorGraph|appealView|Навигатор обращения/i);

const sandbox = { SIMNET_WB: {} };
sandbox.globalThis = sandbox;
vm.createContext(sandbox);
vm.runInContext(contentSource, sandbox);
const catalog = sandbox.SIMNET_WB.operatorCompanionContent;
assert.equal(catalog.types.length, 6);
const phraseCount = catalog.types.reduce((sum, topic) => sum + topic.phrases.length, 0);
assert.equal(phraseCount, 48, 'diagnostic knowledge from the old Graph must be retained');
assert.ok(catalog.search('вылогинивает').some(row => row.typeId === 'apps_slow'));
const playbook = catalog.forAgent('низкая скорость по wifi 300 на всех устройствах');
assert.equal(playbook.mode, 'focused');
assert.ok(playbook.topicIds.includes('low_speed'));
assert.ok(playbook.cards.some(item => item.id === 'wifi_band'));
assert.ok(playbook.cards.some(item => item.id === 'wifi_distance'));
assert.ok(playbook.cards.some(item => item.id === 'multiple_macs'), 'master playbook cards stay local even when not selected for prompt');

console.log('operator_companion_contract_test: PASS', { topics: catalog.types.length, phraseCount, suggested: playbook.suggestedCardIds });
