import assert from 'node:assert/strict';
import fs from 'node:fs';

const manifest = JSON.parse(fs.readFileSync(new URL('../manifest.json', import.meta.url), 'utf8'));
const source = fs.readFileSync(new URL('../src/ui/task-form-assistant.js', import.meta.url), 'utf8');
const scripts = manifest.content_scripts?.[0]?.js || [];

assert.ok(scripts.includes('src/ui/task-form-assistant.js'), 'task form assistant must be loaded on UserSide pages');
assert.match(source, /\/task\\\/save/, 'assistant must recognize native /task/save form');
assert.match(source, /select\[name="typer"\]/, 'assistant must read current task type from native edit select');
assert.match(source, /#taskTypeId/, 'assistant must retain hidden type as auxiliary metadata');
assert.match(source, /#taskId, input\[name="id"\]/, 'assistant must resolve CREATE/EDIT from task id, not launch URL');
assert.doesNotMatch(source, /dialog_edit\/i\.test\(location\.pathname\)/, 'mode must not depend on page pathname');
assert.match(source, /#datedo_id/, 'assistant must validate native work date');
assert.match(source, /#timedo_id/, 'assistant must validate native work time hour');
assert.match(source, /#timedo_id2/, 'assistant must validate native work time minute');
assert.match(source, /#date_unk_id/, 'assistant must distinguish semantic "date unknown" state from hidden field values');
assert.match(source, /division_auto_task_staffids/, 'assistant must read native CREATE brigade assignment without owning it');
assert.match(source, /#dummy_pers_id/, 'assistant must read saved EDIT assignments');
assert.match(source, /division_task_staffids/, 'assistant assignment reader must tolerate native staff-change naming');
assert.match(source, /employeeMultiSelectorErrortask_staffId/, 'assistant must respect native assignment requirement marker');
assert.match(source, /normalizeNativeStaffValidation/, 'assistant must clean up legacy Workbench staff-validation mutations');
assert.match(source, /restoreNativeStaffValidation\(form\)/, 'assistant must restore native UserSide staff validation ownership');
assert.doesNotMatch(source, /form\.noValidate\s*=\s*fieldVisit/, 'assistant must not disable UserSide browser validation');
assert.match(source, /FIELD_VISIT_TYPES = new Set\(\[/, 'field-visit scope must remain an explicit canonical set');
assert.match(source, /'10', '14', '29', '50'/, 'canonical field scope must include proven B2B visits');
assert.match(source, /'1', '2', '15', '17', '60', '61', '66', '68', '126', '140'/, 'canonical field scope must include proven B2C visits');
assert.match(source, /'3', '9', '11', '12', '18', '19', '26', '34', '38', '42', '43', '65', '144'/, 'canonical field scope must include proven technical visits');
assert.match(source, /KNOWN_L1_DIVISION_IDS = new Set\(\['1'\]\)/, 'known L1 division identity may remain available as metadata');
assert.doesNotMatch(source, /field-l1-assignment-invalid/, 'field task must not reject L1/other departments when a brigade is present');
assert.match(source, /field-date-required/, 'field CREATE/type-transition must require date');
assert.match(source, /field-time-required/, 'field CREATE/type-transition must require time');
assert.match(source, /FIELD_MIN_LEAD_MS = 3 \* 60 \* 60 \* 1000/, 'field work must enforce a three-hour minimum lead');
assert.match(source, /field-time-min-lead/, 'field CREATE and material schedule changes must detect times earlier than +3 hours');
assert.match(source, /field-time-past/, 'every field save must reject a planned visit already in the past');
assert.match(source, /field-crew-required/, 'field CREATE/EDIT must require a real brigade');
assert.match(source, /sessionStorage\.setItem/, 'type-transition baseline metadata must survive native form reloads');
assert.match(source, /document\.addEventListener\('submit',[^\n]+true\)/, 'assistant must use delegated submit capture for AJAX-inserted forms');
assert.doesNotMatch(source, /MutationObserver/, 'assistant must not add a continuous DOM scanner');
assert.match(source, /event\.stopImmediatePropagation\(\)/, 'invalid Workbench validation must stop native submit');
assert.match(source, /if \(result && !result\.valid\)/, 'only blocking validation errors may stop submit');
assert.match(source, /Плановое время уже прошло/, 'generic non-field past-time warning must remain available');
assert.match(source, /addIssue\(issues, 'warn', 'work-time-past'/, 'generic non-field past time remains advisory');
assert.match(source, /code: 'field-time-past'/, 'field visit past time must be upgraded to a blocking policy error');
assert.doesNotMatch(source, /deadline-both/, 'native dual deadline fields must not create a false warning');
assert.match(source, /if \(context\?\.mode === 'create'\) \{[\s\S]{0,520}form\.querySelector\(`\[\$\{FILTER_ATTR\}\]`\)\?\.remove\(\);/, 'CREATE must not install or retain the Workbench staff filter');
assert.match(source, /RELOAD_AUTO_STAFF_PATH = '\/task\/reload_auto_staff'/, 'EDIT crew picker must use UserSide native brigade source');
assert.match(source, /simnet-wb-edit-crew-list/, 'EDIT task form must expose an assignment picker');
assert.match(source, /simnet-wb-edit-crew-panel" hidden/, 'large EDIT assignment list must be collapsed by default');
assert.match(source, /Изменить исполнителей/, 'collapsed picker must expose a compact explicit toggle');
assert.doesNotMatch(source, /Workbench · выездная бригада/, 'assignment picker must not show redundant Workbench branding');
assert.doesNotMatch(source, /Бригад: \${/, 'assignment picker must not show redundant assignment counters');
assert.match(source, /isBrigadeLabel/, 'crew validation must distinguish Бр. from arbitrary departments');
assert.match(source, /syncEditCrewSelection/, 'EDIT picker must sync chosen/removal state into the native edit form');
assert.match(source, /target\.matches\?\.\('select\[name=\"typer\"\]'\)/, 'unsaved typer change must be the live activation trigger');
assert.match(source, /ensureEditCrewPicker\(form, \{ refresh: true \}\)/, 'typer change must immediately activate/refresh assignment picker');
assert.match(source, /const shouldShow = Boolean\(context\?\.mode === 'edit'\)/, 'assignment picker must remain available for non-field EDIT so staff can be corrected back');
assert.match(source, /Keep the complete native UserSide division list/, 'EDIT picker must retain departments as well as brigades');
assert.match(source, /Number\(bCrew\) - Number\(aCrew\)/, 'brigades may be sorted first without removing departments');
assert.match(source, /evaluateFieldVisitPolicy\(current, baseline, \{ now: new Date\(\) \}\)/, 'probe must pass a defined timestamp and never reference an undefined now variable');
assert.match(source, /queueMicrotask/, 'crew activation must survive native synchronous change handlers without a MutationObserver');
assert.match(source, /currentIds\.forEach\(id =>/, 'current EDIT assignments omitted by target auto-staff must still be exposed and preserved');
assert.match(source, /input\.setAttribute\(EDIT_CREW_DIVISION_ATTR, id\)/, 'fallback current assignment row must stay UI-only');
assert.match(source, /input\.removeAttribute\('name'\)/, 'Workbench edit picker must not submit a parallel staff field');
assert.match(source, /checked \|\| match/, 'checked brigade must remain visible while filtering');
assert.match(source, /WB\.taskFormAssistant = Object\.freeze/, 'assistant must expose probe/validation API for later typer profiles');

console.log('task_form_assistant_contract_test: PASS');
